version: "3.8"

services:
  bkbs:
    build: .
    container_name: BeiKeBox-solidity
    tty: true
  bkbs-test:
    build: .
    container_name: BeiKeBox-solidity-test
    working_dir: /etc/bkb
    command: truffle test
    depends_on: 
      - ganache
  ganache:
    image: trufflesuite/ganache:latest
    container_name: ganache
    logging:
      driver: "none"
    ports:
      - 8545:8545